spring.application.name=restaurante

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurante
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#Aqui eu habilito a virtual Threads no projeto para o alerta funcionar
spring.threads.virtual.enabled=true

#Essa URL e de trançãoo
pagamento.api.url=http://localhost:9090
